name: Build and Push Docker to ECR

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::238991998648:role/github-ecr-role
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 238991998648.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Image
        run: docker build -t bluegreen-app:${{ github.sha }} .

      - name: Tag Image
        run: |
          docker tag bluegreen-app:${{ github.sha }} \
          238991998648.dkr.ecr.ap-south-1.amazonaws.com/bluegreen-app:${{ github.sha }}

      - name: Push Image
        run: |
          docker push 238991998648.dkr.ecr.ap-south-1.amazonaws.com/bluegreen-app:${{ github.sha }}
