name: Build and Push

on:
  workflow_dispatch:
    inputs:
      color:
        description: "Deployment Color"
        required: true
        type: choice
        options:
          - blue
          - green

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push
        run: |
          IMAGE=238991998648.dkr.ecr.ap-south-1.amazonaws.com/bluegreen-app
          COLOR=${{ github.event.inputs.color }}

          docker build --build-arg COLOR=$COLOR -t $IMAGE:$COLOR .
          docker push $IMAGE:$COLOR
